logs:
  - name: root
    level: INFO
    formatter: "%d%T%m%n"
    appender: 
      - type:  FileLogAppender
        file: log.txt
        formatter: "%d%T%m%n"
      - type: StdoutLogAppender
        formatter: "%d%T%m%n"
  - name: system
    level: DEBUG
    formatter: "%d%T%m%n"
    apender:
      - type: FileLogAppender
        file: log.txt
        formatter: "%d%T%m%n"
      - type: StdoutLogAppender
        formatter: "%d%T%m%n"
system:
  port: 9999
  value: 15
  int_vec: 
    - 10
    - 30
  int_list:
    - 100
    - 200
    - 50
  int_flist:
    - 444
    - 555
  int_set:
    - 777
    - 999
    - 888
    - 777
  int_uset: [111, 222, 333]
  str_int_map: 
    w: 10
    y: 11
    z: 12
  str_int_umap:
    l: 21
    i: 22
    y: 23
class:
  persion:
    name: wyze
    age: 26
    sex: true
  map:
    lili:
      name: lili
      age: 24
      sex: false
  vec_map:
    k1:
      - name: k11
        age: 10
        sex: true
      - name: k12
        age: 20
        sex: false
    k2:
      - name: k21
        age: 30
        sex: true
      - name: k22
        age: 40
        sex: true